package main

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"unicode"

	"golang.org/x/tools/go/packages"
)

const enumxPackage = "akatengu/internal/pkg/enumx"

func generate(pkg *packages.Package, defs map[string]*EnumDef) {
	for _, def := range defs {

		var buf bytes.Buffer

		buf.WriteString(fmt.Sprintf("// Code generated by %s DO NOT EDIT.\n", version))
		buf.WriteString("package " + pkg.Name + "\n\n")
		buf.WriteString(fmt.Sprintf("import \"%s\"\n\n", enumxPackage))

		genEnum(&buf, def)

		file := fileNameFromType(def.TypeName) + "_gen.go"

		full := filepath.Join(pkg.Dir, file)

		fmt.Println("generate:", full)

		os.WriteFile(full, buf.Bytes(), 0644)
	}
}

func generateRegistry(targetPkg *packages.Package, defs []*EnumDef) {

	imports := map[string]string{} // path → alias

	for _, d := range defs {
		if d.PkgPath != targetPkg.PkgPath {
			imports[d.PkgPath] = d.PkgName
		}
	}
	var buf bytes.Buffer

	buf.WriteString(fmt.Sprintf("// Code generated by %s DO NOT EDIT.\n", version))

	buf.WriteString(fmt.Sprintf("package %s\n\n", targetPkg.Name))

	buf.WriteString("import (\n")

	buf.WriteString(fmt.Sprintf("\t\"%s\"\n", enumxPackage))

	for path, name := range imports {
		buf.WriteString(fmt.Sprintf("\t%s \"%s\"\n", name, path))
	}

	buf.WriteString(")\n\n")

	buf.WriteString("func InitEnums() {\n")

	for _, d := range defs {
		pkgPrefix := ""
		if d.PkgPath != targetPkg.PkgPath {
			pkgPrefix = fmt.Sprintf("%s.", d.PkgName)
		}
		buf.WriteString(fmt.Sprintf(`
	enumx.Register(%sAll%s())
`, pkgPrefix, d.Alias))
	}

	buf.WriteString("}\n")

	os.WriteFile("enums_registry_gen.go", buf.Bytes(), 0644)
}

func fileNameFromType(typeName string) string {
	// aggregateTypeVal → aggregate_type
	name := strings.TrimSuffix(typeName, "Val")

	var out []rune
	for i, r := range name {
		if i > 0 && unicode.IsUpper(r) {
			out = append(out, '_')
		}
		out = append(out, unicode.ToLower(r))
	}
	return string(out)
}

func genEnum(buf *bytes.Buffer, def *EnumDef) {
	typeName := def.TypeName // aggregateTypeVal
	enumName := def.Alias    // AggregateType

	// Enum()
	buf.WriteString(fmt.Sprintf(`
func (v %s) Enum() %s {
	return enumx.Must[%s](v)
}
`, typeName, enumName, typeName))

	// Enum()
	buf.WriteString(fmt.Sprintf(`
func (v %s) String() string {
	return string(v)
}
`, typeName))

	// Parse
	buf.WriteString(fmt.Sprintf(`
func Parse%s(s string) (%s, error) {
	return enumx.Parse[%s](s)
}
`, enumName, enumName, typeName))

	// All
	buf.WriteString(fmt.Sprintf(`
func All%s() []%s {
	return []%s{
`, enumName, typeName, typeName))

	for _, c := range def.Consts {
		buf.WriteString("\t\t" + c.Name + ",\n")
	}
	buf.WriteString("\t}\n}\n")

	// Labels
	buf.WriteString(fmt.Sprintf(`
func %sLabels() map[%s]string {
	return map[%s]string{
`, enumName, typeName, typeName))

	for _, c := range def.Consts {
		label := c.Label
		if label == "" {
			label = c.Name
		}
		buf.WriteString(fmt.Sprintf("\t\t%s: \"%s\",\n", c.Name, label))
	}
	buf.WriteString("\t}\n}\n")
}
